# Generated by Django 6.0.5 on 2026-05-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato'), ('CONVENIO', 'Convênio')], max_length=20)),
                ('objeto', models.TextField()),
                ('fornecedor', models.CharField(max_length=150)),
                ('responsavel', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('inicio', models.CharField()),
                ('termino', models.CharField()),
                ('cidade', models.CharField()),
                ('nome_fantasia', models.CharField(blank=True, default='')),
                ('cnpj', models.CharField(blank=True)),
            ],
        ),
    ]
